# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddM(object):
    def setupUi(self, AddM):
        AddM.setObjectName("AddM")
        AddM.resize(640, 500)
        self.AddTab = QtWidgets.QTabWidget(AddM)
        self.AddTab.setGeometry(QtCore.QRect(20, 10, 611, 461))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AddTab.setFont(font)
        self.AddTab.setObjectName("AddTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.DAddDB = QtWidgets.QPushButton(self.tab)
        self.DAddDB.setGeometry(QtCore.QRect(250, 150, 93, 28))
        self.DAddDB.setObjectName("DAddDB")
        self.DcomboBox = QtWidgets.QComboBox(self.tab)
        self.DcomboBox.setGeometry(QtCore.QRect(30, 60, 261, 31))
        self.DcomboBox.setObjectName("DcomboBox")
        self.DcomboBox.addItem("")
        self.DcomboBox.addItem("")
        self.DcomboBox.addItem("")
        self.DAmount = QtWidgets.QLineEdit(self.tab)
        self.DAmount.setGeometry(QtCore.QRect(410, 60, 151, 31))
        self.DAmount.setObjectName("DAmount")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(110, 10, 131, 41))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setGeometry(QtCore.QRect(450, 20, 81, 31))
        self.label_2.setObjectName("label_2")
        self.ResIns = QtWidgets.QLabel(self.tab)
        self.ResIns.setGeometry(QtCore.QRect(120, 270, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ResIns.setFont(font)
        self.ResIns.setText("")
        self.ResIns.setObjectName("ResIns")
        self.AddTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.GAddDB = QtWidgets.QPushButton(self.tab_2)
        self.GAddDB.setGeometry(QtCore.QRect(240, 260, 93, 28))
        self.GAddDB.setObjectName("GAddDB")
        self.GDis = QtWidgets.QLineEdit(self.tab_2)
        self.GDis.setGeometry(QtCore.QRect(40, 80, 501, 31))
        self.GDis.setObjectName("GDis")
        self.GAmount = QtWidgets.QLineEdit(self.tab_2)
        self.GAmount.setGeometry(QtCore.QRect(50, 200, 141, 31))
        self.GAmount.setObjectName("GAmount")
        self.label_9 = QtWidgets.QLabel(self.tab_2)
        self.label_9.setGeometry(QtCore.QRect(50, 30, 131, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_2)
        self.label_10.setGeometry(QtCore.QRect(50, 160, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.ResIns_2 = QtWidgets.QLabel(self.tab_2)
        self.ResIns_2.setGeometry(QtCore.QRect(80, 340, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ResIns_2.setFont(font)
        self.ResIns_2.setText("")
        self.ResIns_2.setObjectName("ResIns_2")
        self.AddTab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.BAddDB_2 = QtWidgets.QPushButton(self.tab_3)
        self.BAddDB_2.setGeometry(QtCore.QRect(280, 360, 93, 28))
        self.BAddDB_2.setObjectName("BAddDB_2")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_3)
        self.comboBox_2.setGeometry(QtCore.QRect(30, 70, 261, 31))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(110, 20, 131, 41))
        self.label_3.setObjectName("label_3")
        self.BAmount = QtWidgets.QLineEdit(self.tab_3)
        self.BAmount.setGeometry(QtCore.QRect(410, 70, 151, 31))
        self.BAmount.setObjectName("BAmount")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(450, 30, 81, 31))
        self.label_4.setObjectName("label_4")
        self.AddTab.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.OAmount = QtWidgets.QLineEdit(self.tab_4)
        self.OAmount.setGeometry(QtCore.QRect(370, 100, 141, 31))
        self.OAmount.setObjectName("OAmount")
        self.ODis = QtWidgets.QLineEdit(self.tab_4)
        self.ODis.setGeometry(QtCore.QRect(50, 100, 211, 31))
        self.ODis.setObjectName("ODis")
        self.OAddDB = QtWidgets.QPushButton(self.tab_4)
        self.OAddDB.setGeometry(QtCore.QRect(240, 190, 93, 28))
        self.OAddDB.setObjectName("OAddDB")
        self.label_11 = QtWidgets.QLabel(self.tab_4)
        self.label_11.setGeometry(QtCore.QRect(90, 50, 131, 41))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_4)
        self.label_12.setGeometry(QtCore.QRect(400, 60, 81, 31))
        self.label_12.setObjectName("label_12")
        self.ResIns_3 = QtWidgets.QLabel(self.tab_4)
        self.ResIns_3.setGeometry(QtCore.QRect(90, 290, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.ResIns_3.setFont(font)
        self.ResIns_3.setText("")
        self.ResIns_3.setObjectName("ResIns_3")
        self.AddTab.addTab(self.tab_4, "")

        self.retranslateUi(AddM)
        self.AddTab.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(AddM)

    def retranslateUi(self, AddM):
        _translate = QtCore.QCoreApplication.translate
        AddM.setWindowTitle(_translate("AddM", "Add Expence"))
        self.DAddDB.setText(_translate("AddM", "Add "))
        self.DcomboBox.setItemText(0, _translate("AddM", "Food"))
        self.DcomboBox.setItemText(1, _translate("AddM", "Travel"))
        self.DcomboBox.setItemText(2, _translate("AddM", "Personal"))
        self.label.setText(_translate("AddM", "Select Catagory"))
        self.label_2.setText(_translate("AddM", "Spent"))
        self.AddTab.setTabText(self.AddTab.indexOf(self.tab), _translate("AddM", "Daily Expense"))
        self.GAddDB.setText(_translate("AddM", "Add"))
        self.label_9.setText(_translate("AddM", "Item"))
        self.label_10.setText(_translate("AddM", "Spent"))
        self.AddTab.setTabText(self.AddTab.indexOf(self.tab_2), _translate("AddM", "Grocery"))
        self.BAddDB_2.setText(_translate("AddM", "Add"))
        self.comboBox_2.setItemText(0, _translate("AddM", "Electricity"))
        self.comboBox_2.setItemText(1, _translate("AddM", "Mobile"))
        self.comboBox_2.setItemText(2, _translate("AddM", "Room Rent"))
        self.comboBox_2.setItemText(3, _translate("AddM", "Water"))
        self.comboBox_2.setItemText(4, _translate("AddM", "Television"))
        self.comboBox_2.setItemText(5, _translate("AddM", "Gas "))
        self.comboBox_2.setItemText(6, _translate("AddM", "Wifi"))
        self.label_3.setText(_translate("AddM", "Select Catagory"))
        self.label_4.setText(_translate("AddM", "Spent"))
        self.AddTab.setTabText(self.AddTab.indexOf(self.tab_3), _translate("AddM", "Bills"))
        self.OAddDB.setText(_translate("AddM", "Add"))
        self.label_11.setText(_translate("AddM", "Item"))
        self.label_12.setText(_translate("AddM", "Spent"))
        self.AddTab.setTabText(self.AddTab.indexOf(self.tab_4), _translate("AddM", "Other"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddM = QtWidgets.QDialog()
    ui = Ui_AddM()
    ui.setupUi(AddM)
    AddM.show()
    sys.exit(app.exec_())
