# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'History.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HistM(object):
    def setupUi(self, HistM):
        HistM.setObjectName("HistM")
        HistM.resize(777, 542)
        self.SeachTab = QtWidgets.QTabWidget(HistM)
        self.SeachTab.setGeometry(QtCore.QRect(10, 30, 751, 481))
        font = QtGui.QFont()
        font.setFamily("Sanskrit Text")
        font.setPointSize(12)
        self.SeachTab.setFont(font)
        self.SeachTab.setObjectName("SeachTab")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.DS = QtWidgets.QDateEdit(self.tab)
        self.DS.setGeometry(QtCore.QRect(30, 20, 171, 31))
        self.DS.setObjectName("DS")
        self.tableView = QtWidgets.QTableView(self.tab)
        self.tableView.setGeometry(QtCore.QRect(20, 60, 721, 371))
        self.tableView.setObjectName("tableView")
        self.DSRbt = QtWidgets.QPushButton(self.tab)
        self.DSRbt.setGeometry(QtCore.QRect(260, 20, 93, 28))
        self.DSRbt.setObjectName("DSRbt")
        self.DSRes = QtWidgets.QLabel(self.tab)
        self.DSRes.setGeometry(QtCore.QRect(430, 30, 251, 16))
        self.DSRes.setObjectName("DSRes")
        self.SeachTab.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.MS = QtWidgets.QComboBox(self.tab_2)
        self.MS.setGeometry(QtCore.QRect(30, 10, 181, 31))
        self.MS.setObjectName("MS")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MS.addItem("")
        self.MSRbt = QtWidgets.QPushButton(self.tab_2)
        self.MSRbt.setGeometry(QtCore.QRect(280, 10, 91, 31))
        self.MSRbt.setObjectName("MSRbt")
        self.MSRes = QtWidgets.QLabel(self.tab_2)
        self.MSRes.setGeometry(QtCore.QRect(470, 20, 201, 21))
        self.MSRes.setObjectName("MSRes")
        self.tableView_2 = QtWidgets.QTableView(self.tab_2)
        self.tableView_2.setGeometry(QtCore.QRect(10, 50, 731, 381))
        self.tableView_2.setObjectName("tableView_2")
        self.SeachTab.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.P1S = QtWidgets.QDateEdit(self.tab_3)
        self.P1S.setGeometry(QtCore.QRect(10, 10, 171, 31))
        self.P1S.setObjectName("P1S")
        self.P2S = QtWidgets.QDateEdit(self.tab_3)
        self.P2S.setGeometry(QtCore.QRect(270, 10, 171, 31))
        self.P2S.setObjectName("P2S")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(210, 20, 55, 16))
        self.label_4.setObjectName("label_4")
        self.PSRes = QtWidgets.QLabel(self.tab_3)
        self.PSRes.setGeometry(QtCore.QRect(550, 20, 201, 21))
        self.PSRes.setObjectName("PSRes")
        self.PSRbt = QtWidgets.QPushButton(self.tab_3)
        self.PSRbt.setGeometry(QtCore.QRect(450, 10, 91, 31))
        self.PSRbt.setObjectName("PSRbt")
        self.tableView_3 = QtWidgets.QTableView(self.tab_3)
        self.tableView_3.setGeometry(QtCore.QRect(10, 50, 731, 381))
        self.tableView_3.setObjectName("tableView_3")
        self.SeachTab.addTab(self.tab_3, "")
        self.label = QtWidgets.QLabel(HistM)
        self.label.setGeometry(QtCore.QRect(30, 0, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Sanskrit Text")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(HistM)
        self.SeachTab.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(HistM)

    def retranslateUi(self, HistM):
        _translate = QtCore.QCoreApplication.translate
        HistM.setWindowTitle(_translate("HistM", "History"))
        self.DSRbt.setText(_translate("HistM", "Seach"))
        self.DSRes.setText(_translate("HistM", "TextLabel"))
        self.SeachTab.setTabText(self.SeachTab.indexOf(self.tab), _translate("HistM", "Day"))
        self.MS.setItemText(0, _translate("HistM", "January"))
        self.MS.setItemText(1, _translate("HistM", "February"))
        self.MS.setItemText(2, _translate("HistM", "March"))
        self.MS.setItemText(3, _translate("HistM", "April"))
        self.MS.setItemText(4, _translate("HistM", "May"))
        self.MS.setItemText(5, _translate("HistM", "June"))
        self.MS.setItemText(6, _translate("HistM", "July"))
        self.MS.setItemText(7, _translate("HistM", "August"))
        self.MS.setItemText(8, _translate("HistM", "Sapteber"))
        self.MS.setItemText(9, _translate("HistM", "October"))
        self.MS.setItemText(10, _translate("HistM", "November"))
        self.MS.setItemText(11, _translate("HistM", "December"))
        self.MSRbt.setText(_translate("HistM", "Seach"))
        self.MSRes.setText(_translate("HistM", "TextLabel"))
        self.SeachTab.setTabText(self.SeachTab.indexOf(self.tab_2), _translate("HistM", "Month"))
        self.label_4.setText(_translate("HistM", "To"))
        self.PSRes.setText(_translate("HistM", "TextLabel"))
        self.PSRbt.setText(_translate("HistM", "Seach"))
        self.SeachTab.setTabText(self.SeachTab.indexOf(self.tab_3), _translate("HistM", "Period"))
        self.label.setText(_translate("HistM", "Seach by :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    HistM = QtWidgets.QDialog()
    ui = Ui_HistM()
    ui.setupUi(HistM)
    HistM.show()
    sys.exit(app.exec_())
